"""
grid_quantum_sampler.py

Summary:
    Provides the quantum-guided candidate selection step used by qRRT.

    The qRRT planner first generates a local set of valid grid candidates.
    This module then scores those candidates by progress toward the goal,
    marks the best candidates as "good", and calls the Grover/oracle utilities
    in oracle_qiskit.py to produce a probability distribution over candidates.

    The final selected candidate is sampled from that Grover-weighted
    probability distribution.

    Important:
        This module does not generate candidates by itself. It only selects
        from a candidate list that was already generated and filtered by the
        planner.

    In the current implementation, "good" candidates are the top-k candidates
    closest to the goal in grid-index distance.
"""

from __future__ import annotations

from typing import List, Sequence, Tuple

import numpy as np

from qrrt_planner.oracle_qiskit import (
    grover_weights_for_region,
    sample_index_from_probs,
)

# A grid index is a tuple of integer bin positions, one per robot joint.
# Example for a 6-DOF arm:
#     (5, 5, 7, 5, 2, 7)
GridIndex = Tuple[int, ...]


def grid_idx_distance(a: GridIndex, b: GridIndex) -> float:
    """
    Compute Euclidean distance between two grid indices.

    This distance is measured in grid-index space, not physical workspace.
    It is used as a simple progress heuristic toward the goal.

    Args:
        a:
            First grid index.
        b:
            Second grid index.

    Returns:
        Euclidean distance between the two grid indices.
    """
    return float(np.linalg.norm(np.asarray(a, dtype=float) - np.asarray(b, dtype=float)))


def choose_good_candidate_indices(
    candidates: Sequence[GridIndex],
    goal_idx: GridIndex,
    progress_weight: float = 1.0,
    top_k: int = 8,
) -> List[int]:
    """
    Choose which candidates should be marked as "good" for Grover selection.

    Candidates are scored by negative distance to the goal. This means
    candidates closer to the goal receive higher scores. The top_k best-scoring
    candidates are returned as indices into the candidate list.

    Args:
        candidates:
            Candidate grid states generated by the qRRT planner.
        goal_idx:
            Goal grid index.
        progress_weight:
            Weight applied to the distance-to-goal score.
        top_k:
            Number of candidates to mark as good.

    Returns:
        List of integer candidate-list positions to mark as good.
    """
    if not candidates:
        return []

    scored = []
    for i, idx in enumerate(candidates):
        d_goal = grid_idx_distance(idx, goal_idx)
        score = -progress_weight * d_goal
        scored.append((score, i))

    # Highest score first. Since score is negative distance, this puts
    # candidates closest to the goal first.
    scored.sort(reverse=True)

    k = max(1, min(top_k, len(scored)))
    return [i for _, i in scored[:k]]


def quantum_select_grid_candidate(
    candidates: Sequence[GridIndex],
    goal_idx: GridIndex,
    rng: np.random.Generator,
    top_k: int = 8,
    n_iters: int = 1,
    shots: int = 64,
    use_ibm: bool = False,
    ibm_backend_name: str = "ibm_torino",
    ibm_channel: str | None = None,
    progress_weight: float = 1.0,
) -> GridIndex:
    """
    Select one grid candidate using Grover-weighted probabilities.

    Steps:
        1. Score candidates by progress toward the goal.
        2. Mark the top_k candidates as "good".
        3. Build/run the Grover-style probability model using oracle_qiskit.py.
        4. Sample one candidate index from the returned probability distribution.
        5. Return the corresponding grid candidate.

    Args:
        candidates:
            Valid local grid candidates produced by qRRT.
        goal_idx:
            Goal grid index.
        rng:
            NumPy random generator used for reproducible sampling.
        top_k:
            Number of candidates marked as good.
        n_iters:
            Number of Grover iterations.
        shots:
            Number of circuit shots/samples used by the quantum simulation or backend.
        use_ibm:
            If True, use an IBM backend path if supported by oracle_qiskit.py.
            If False, use the local simulator/probability path.
        ibm_backend_name:
            IBM backend name, used only when use_ibm is True.
        ibm_channel:
            Optional IBM channel name, used only when use_ibm is True.
        progress_weight:
            Weight applied when scoring progress toward the goal.

    Returns:
        Selected grid candidate.

    Raises:
        ValueError:
            If the candidate list is empty.
    """
    if not candidates:
        raise ValueError("No candidates provided to quantum_select_grid_candidate")

    # Determine which candidate indices should be amplified by Grover.
    good_indices = choose_good_candidate_indices(
        candidates=candidates,
        goal_idx=goal_idx,
        progress_weight=progress_weight,
        top_k=top_k,
    )

    # Get Grover-weighted probabilities over all candidate indices.
    # The returned probability vector has length len(candidates).
    probs = grover_weights_for_region(
        n_states=len(candidates),
        good_indices=good_indices,
        n_iters=n_iters,
        shots=shots,
        use_ibm=use_ibm,
        ibm_backend_name=ibm_backend_name,
        ibm_channel=ibm_channel,
        return_counts=False,
    )

    # Sample one candidate index according to the Grover-weighted distribution.
    chosen = int(sample_index_from_probs(probs, rng=rng))
    return candidates[chosen]
