"""
qrrt_grid.py

Summary:
    Implements Quantum-guided RRT on a discretized joint-space grid.

    Each grid index represents one possible robot joint configuration. The
    planner grows a tree from the start grid state toward randomly sampled
    target grid states. At each expansion, it finds the nearest existing tree
    node, builds an unordered local database of valid neighboring candidates,
    and uses Grover improvement search to select a strong tree-extension
    candidate from that unordered database.

    This planner is compared against:
        - Classical grid-RRT in crrt_grid.py
        - Grid A* in grid_joint_space.py / benchmark_grid_astar.py

    Important:
        The quantum step only selects from the candidate set generated by the
        planner. If the requested quantum_candidates value is large but the
        local valid candidate set is small, the actual Grover circuit will use
        only the number of candidates that survived filtering.
"""

from __future__ import annotations

import random
from dataclasses import dataclass
from typing import Callable, Dict, List, Optional, Sequence, Tuple

import numpy as np

from qrrt_planner.grid_joint_space import (
    GridIndex,
    grid_neighbors,
    make_grid_edge_checker,
    make_grid_validity_checker,
    nearest_valid_grid_index,
    q_to_grid,
)
from qrrt_planner.grid_quantum_sampler import quantum_select_grid_candidate


# Type alias for a grid-state validity checker.
GridStateValidFn = Callable[[GridIndex], bool]

# Type alias for a grid-edge validity checker.
GridEdgeValidFn = Callable[[GridIndex, GridIndex], bool]


@dataclass
class GridNode:
    """
    One node in the RRT tree.

    Attributes:
        idx:
            Grid index for this robot configuration.
        parent:
            Index of this node's parent in the nodes list.
            The root node has parent=None.
    """
    idx: GridIndex
    parent: Optional[int] = None


def nearest_index_in_tree(nodes: List[GridNode], target: GridIndex) -> int:
    """
    Find the existing tree node closest to a target grid index.

    Args:
        nodes:
            Current RRT tree nodes.
        target:
            Target grid index.

    Returns:
        Integer index of the nearest node in the nodes list.
    """
    target_np = np.asarray(target, dtype=float)
    best_i = 0
    best_d = float(np.linalg.norm(np.asarray(nodes[0].idx, dtype=float) - target_np))

    for i in range(1, len(nodes)):
        d = float(np.linalg.norm(np.asarray(nodes[i].idx, dtype=float) - target_np))
        if d < best_d:
            best_d = d
            best_i = i

    return best_i


def reconstruct_grid_path(nodes: List[GridNode], goal_node_index: int) -> List[GridIndex]:
    """
    Reconstruct a path by following parent links from the goal node to the root.

    Args:
        nodes:
            Full RRT tree.
        goal_node_index:
            Index of the final goal node.

    Returns:
        Ordered grid path from start to goal.
    """
    path: List[GridIndex] = []
    i = goal_node_index

    while i is not None:
        path.append(nodes[i].idx)
        i = nodes[i].parent

    path.reverse()
    return path


def grid_goal_reached(current: GridIndex, goal: GridIndex, goal_radius_idx: float) -> bool:
    """
    Check whether a grid state is within the goal radius.

    Args:
        current:
            Current grid index.
        goal:
            Goal grid index.
        goal_radius_idx:
            Goal radius measured in grid-index distance.

    Returns:
        True if current is close enough to the goal.
    """
    d = float(np.linalg.norm(np.asarray(current, dtype=float) - np.asarray(goal, dtype=float)))
    return d <= goal_radius_idx


def sample_random_grid_index(shape: Sequence[int]) -> GridIndex:
    """
    Uniformly sample a random grid index.

    Args:
        shape:
            Number of bins in each joint dimension.

    Returns:
        Random grid index tuple.
    """
    return tuple(random.randrange(shape[d]) for d in range(len(shape)))


def local_candidate_set(
    center_idx: GridIndex,
    shape: Sequence[int],
    is_valid_idx: GridStateValidFn,
    edge_valid_idx: GridEdgeValidFn,
    max_candidates: int = 64,
    max_radius: int = 2,
    excluded: Optional[set[GridIndex]] = None,
) -> List[GridIndex]:
    """
    Build a local set of valid candidate states near a tree node.

    The search expands outward from center_idx through grid neighbors. A
    neighbor is kept as a candidate only if:
        1. the state is valid,
        2. the edge from center_idx to that state is valid,
        3. it has not already been added to this candidate set,
        4. it is not already in the tree, when excluded is provided.

    Args:
        center_idx:
            Grid state around which candidates are generated.
        shape:
            Grid dimensions.
        is_valid_idx:
            Cached grid-state validity checker.
        edge_valid_idx:
            Cached grid-edge validity checker.
        max_candidates:
            Maximum number of candidates to return.
        max_radius:
            Maximum number of neighbor-expansion layers.
        excluded:
            Optional set of grid states to keep out of the candidate database,
            usually the states already present in the RRT tree.

    Returns:
        List of valid local candidate grid indices.
    """
    candidates: List[GridIndex] = []
    seen = set()
    excluded = excluded or set()

    frontier = [center_idx]
    visited = {center_idx}

    for _ in range(max_radius):
        new_frontier: List[GridIndex] = []
        for idx in frontier:
            for nbr in grid_neighbors(idx, shape):
                if nbr in visited:
                    continue
                visited.add(nbr)

                if nbr in excluded:
                    continue
                if not is_valid_idx(nbr):
                    continue
                if not edge_valid_idx(center_idx, nbr):
                    continue
                if nbr in seen:
                    continue

                seen.add(nbr)
                candidates.append(nbr)
                new_frontier.append(nbr)

                if len(candidates) >= max_candidates:
                    return candidates

        frontier = new_frontier
        if not frontier:
            break

    return candidates


def qrrt_grid(
    q_start: Sequence[float],
    q_goal: Sequence[float],
    bins: Sequence[np.ndarray],
    state_valid_fn,
    max_iters: int = 5000,
    goal_sample_rate: float = 0.10,
    goal_radius_idx: float = 0.0,
    edge_step: float = 0.05,
    quantum_candidates: int = 64,
    quantum_iters: int = 1,
    quantum_shots: int = 64,
    quantum_use_ibm: bool = False,
    quantum_backend: str = "ibm_torino",
    quantum_target_weight: float = 1.0,
    quantum_goal_weight: float = 1.0,
    quantum_best_rounds: int = 3,
    quantum_score_margin: float = 1e-9,
    rng_seed: int = 0,
    debug: bool = False,
):
    """
    Run quantum-guided RRT over a discretized joint-space grid.

    Args:
        q_start:
            Continuous start joint configuration.
        q_goal:
            Continuous goal joint configuration.
        bins:
            Discretized joint values for each joint.
        state_valid_fn:
            Function that checks whether a continuous joint state is valid.
        max_iters:
            Maximum number of RRT iterations.
        goal_sample_rate:
            Probability of sampling the goal instead of a random grid state.
        goal_radius_idx:
            Goal radius in grid-index distance.
        edge_step:
            Step size used for edge validity checking.
        quantum_candidates:
            Maximum number of local candidates to consider per expansion.
        quantum_iters:
            Number of Grover iterations.
        quantum_shots:
            Number of measurement shots used by the quantum sampler.
        quantum_use_ibm:
            If True, use an IBM backend path where supported.
        quantum_backend:
            IBM backend name.
        quantum_target_weight:
            Weight applied to progress toward the current RRT target.
        quantum_goal_weight:
            Weight applied to progress toward the final goal.
        quantum_best_rounds:
            Number of Grover improvement rounds used to search for a better
            candidate in the unordered database.
        quantum_score_margin:
            Minimum score improvement required to replace the incumbent.
        rng_seed:
            Random seed for reproducible runs.
        debug:
            If True, store per-iteration trace information.

    Returns:
        Tuple:
            path:
                List of grid indices from start to goal, or None on failure.
            stats:
                Dictionary of planner metrics.
    """
    rng = np.random.default_rng(rng_seed)
    random.seed(rng_seed)

    shape = tuple(len(b) for b in bins)
    start_idx_raw = q_to_grid(q_start, bins)
    goal_idx_raw = q_to_grid(q_goal, bins)

    # Create grid-level validity and edge-checking functions from the continuous
    # MoveIt collision checker.
    is_valid_idx = make_grid_validity_checker(bins, state_valid_fn)
    edge_valid_idx = make_grid_edge_checker(bins, state_valid_fn, edge_step)

    # Snap start and goal to nearby valid grid cells.
    start_idx = nearest_valid_grid_index(start_idx_raw, shape, is_valid_idx, max_radius=3)
    goal_idx = nearest_valid_grid_index(goal_idx_raw, shape, is_valid_idx, max_radius=3)

    if start_idx is None:
        raise ValueError("No valid grid state found near start")
    if goal_idx is None:
        raise ValueError("No valid grid state found near goal")

    # Initialize RRT tree at the snapped start grid index.
    nodes: List[GridNode] = [GridNode(idx=start_idx, parent=None)]
    visited_tree = {start_idx}

    # Metrics collected for reporting and CSV output.
    stats: Dict[str, object] = {
        "planner_type": "qrrt_grid",
        "success": False,
        "iterations": 0,
        "nodes": 1,
        "start_idx_raw": start_idx_raw,
        "goal_idx_raw": goal_idx_raw,
        "start_idx": start_idx,
        "goal_idx": goal_idx,
        "quantum_calls": 0,
        "quantum_successful_extensions": 0,
        "invalid_random_targets": 0,
        "empty_candidate_sets": 0,
        "goal_sample_hits": 0,
        "duplicate_rejections": 0,
        "invalid_chosen_state_rejections": 0,
        "invalid_chosen_edge_rejections": 0,
        "candidate_count_total": 0,
        "candidate_count_nonempty_iters": 0,
        "marked_set_size_total": 0,
        "grover_rounds_total": 0,
        "selected_score_total": 0.0,
        "initial_score_total": 0.0,
        "grover_improvements": 0,
        "path_waypoints": None,
        "trace": [] if debug else None,
    }

    for it in range(max_iters):
        stats["iterations"] = it + 1

        # With probability goal_sample_rate, sample the goal directly.
        # Otherwise sample a random grid state.
        goal_sampled = random.random() < goal_sample_rate

        if goal_sampled:
            q_rand_idx = goal_idx
            stats["goal_sample_hits"] = int(stats["goal_sample_hits"]) + 1
        else:
            q_rand_idx = sample_random_grid_index(shape)

        # Reject random target states that are invalid.
        if not is_valid_idx(q_rand_idx):
            stats["invalid_random_targets"] = int(stats["invalid_random_targets"]) + 1
            if debug:
                stats["trace"].append({
                    "iteration": it + 1,
                    "goal_sampled": goal_sampled,
                    "candidate_count": 0,
                    "chosen_idx": None,
                    "chosen_score": None,
                    "initial_score": None,
                    "grover_rounds": 0,
                    "accepted": False,
                    "rejection_reason": "invalid_random_target",
                    "tree_nodes": len(nodes),
                })
            continue

        # Find the closest existing tree node to the sampled target.
        i_near = nearest_index_in_tree(nodes, q_rand_idx)
        idx_near = nodes[i_near].idx

        # Build the candidate database for this expansion.
        candidates = local_candidate_set(
            center_idx=idx_near,
            shape=shape,
            is_valid_idx=is_valid_idx,
            edge_valid_idx=edge_valid_idx,
            max_candidates=quantum_candidates,
            max_radius=2,
            excluded=visited_tree,
        )

        stats["candidate_count_total"] = int(stats["candidate_count_total"]) + len(candidates)

        if not candidates:
            stats["empty_candidate_sets"] = int(stats["empty_candidate_sets"]) + 1
            if debug:
                stats["trace"].append({
                    "iteration": it + 1,
                    "goal_sampled": goal_sampled,
                    "candidate_count": 0,
                    "chosen_idx": None,
                    "chosen_score": None,
                    "initial_score": None,
                    "grover_rounds": 0,
                    "accepted": False,
                    "rejection_reason": "empty_candidate_set",
                    "tree_nodes": len(nodes),
                })
            continue

        stats["candidate_count_nonempty_iters"] = int(stats["candidate_count_nonempty_iters"]) + 1
        stats["quantum_calls"] = int(stats["quantum_calls"]) + 1

        # Randomize database order before encoding candidates as basis states.
        # Grover receives an unordered valid-candidate database.
        order = rng.permutation(len(candidates))
        candidates = [candidates[int(i)] for i in order]

        # Select a candidate with Grover improvement search. No candidate
        # ranking or top-k classical preselection is performed here.
        selection = quantum_select_grid_candidate(
            candidates=candidates,
            near_idx=idx_near,
            target_idx=q_rand_idx,
            goal_idx=goal_idx,
            rng=rng,
            n_iters=quantum_iters,
            shots=quantum_shots,
            use_ibm=quantum_use_ibm,
            ibm_backend_name=quantum_backend,
            target_weight=quantum_target_weight,
            goal_weight=quantum_goal_weight,
            best_rounds=quantum_best_rounds,
            score_margin=quantum_score_margin,
        )
        idx_new = selection.candidate

        stats["marked_set_size_total"] = (
            int(stats["marked_set_size_total"]) + selection.marked_count_total
        )
        stats["grover_rounds_total"] = (
            int(stats["grover_rounds_total"]) + selection.grover_rounds
        )
        stats["selected_score_total"] = (
            float(stats["selected_score_total"]) + selection.selected_score
        )
        stats["initial_score_total"] = (
            float(stats["initial_score_total"]) + selection.initial_score
        )
        if selection.improved:
            stats["grover_improvements"] = int(stats["grover_improvements"]) + 1

        rejection_reason = None
        accepted = False

        # Validate and add the selected candidate to the tree.
        if idx_new in visited_tree:
            stats["duplicate_rejections"] = int(stats["duplicate_rejections"]) + 1
            rejection_reason = "duplicate"
        elif not is_valid_idx(idx_new):
            stats["invalid_chosen_state_rejections"] = int(stats["invalid_chosen_state_rejections"]) + 1
            rejection_reason = "invalid_chosen_state"
        elif not edge_valid_idx(idx_near, idx_new):
            stats["invalid_chosen_edge_rejections"] = int(stats["invalid_chosen_edge_rejections"]) + 1
            rejection_reason = "invalid_chosen_edge"
        else:
            nodes.append(GridNode(idx=idx_new, parent=i_near))
            visited_tree.add(idx_new)
            stats["nodes"] = len(nodes)
            stats["quantum_successful_extensions"] = int(stats["quantum_successful_extensions"]) + 1
            accepted = True

            # If the new node reaches the goal and the final edge is valid,
            # append the goal and return the path.
            if grid_goal_reached(idx_new, goal_idx, goal_radius_idx):
                if edge_valid_idx(idx_new, goal_idx):
                    nodes.append(GridNode(idx=goal_idx, parent=len(nodes) - 1))
                    stats["nodes"] = len(nodes)
                    stats["success"] = True
                    path = reconstruct_grid_path(nodes, len(nodes) - 1)
                    stats["path_waypoints"] = len(path)

                    if debug:
                        stats["trace"].append({
                            "iteration": it + 1,
                            "goal_sampled": goal_sampled,
                            "candidate_count": len(candidates),
                            "chosen_idx": idx_new,
                            "chosen_score": selection.selected_score,
                            "initial_score": selection.initial_score,
                            "grover_rounds": selection.grover_rounds,
                            "accepted": True,
                            "rejection_reason": None,
                            "tree_nodes": len(nodes),
                        })

                    return path, stats

        if debug:
            stats["trace"].append({
                "iteration": it + 1,
                "goal_sampled": goal_sampled,
                "candidate_count": len(candidates),
                "chosen_idx": idx_new,
                "chosen_score": selection.selected_score,
                "initial_score": selection.initial_score,
                "grover_rounds": selection.grover_rounds,
                "accepted": accepted,
                "rejection_reason": rejection_reason,
                "tree_nodes": len(nodes),
            })

    # If max_iters is reached without reaching the goal, report failure.
    return None, stats
